### ISSUE TITLE
npm run dev/preview is broken 

### ISSUE THREAD

**Issue by natesheehan** [LOOSE-LIPS/loose-lips-2.0#61]

**Comment by natesheehan** [comment]
Something to do with sander and sorcery

**Comment by natesheehan** [comment]
```

Pre-bundling dependencies:
  svelte/store
  svelte
  svelte/transition
  nprogress
  svelte/animate
  (...and 5 more)
(this will be run only when your dependencies or config have changed)
 > node_modules/svelte-preprocess/dist/transformers/coffeescript.js:7:47: error: Could not resolve "coffeescript" (use "./coffeescript" to reference the file "node_modules/svelte-preprocess/dist/transformers/coffeescript.js")
    7 │ const coffeescript_1 = __importDefault(require("coffeescript"));
      ╵                                                ~~~~~~~~~~~~~~

 > node_modules/svelte-preprocess/dist/transformers/stylus.js:8:41: error: Could not resolve "stylus" (use "./stylus" to reference the file "node_modules/svelte-preprocess/dist/transformers/stylus.js")
    8 │ const stylus_1 = __importDefault(require("stylus"));
      ╵                                          ~~~~~~~~

 > node_modules/svelte-preprocess/dist/modules/language.js:27:24: error: Could not resolve "sugarss" (mark it as external to exclude it from the bundle, or surround it 
with try/catch to handle the failure at run-time)
    27 │         parser: require('sugarss'),
       ╵                         ~~~~~~~~~

 > node_modules/svelte-preprocess/dist/transformers/pug.js:8:38: error: Could not resolve "pug" (use "./pug" to reference the file "node_modules/svelte-preprocess/dist/transformers/pug.js")
    8 │ const pug_1 = __importDefault(require("pug"));
      ╵                                       ~~~~~

 > node_modules/svelte-preprocess/dist/transformers/less.js:8:39: error: Could not resolve "less" (use "./less" to reference the file "node_modules/svelte-preprocess/dist/transformers/less.js")
    8 │ const less_1 = __importDefault(require("less"));
      ╵                                        ~~~~~~

> Build failed with 5 errors:
node_modules/svelte-preprocess/dist/modules/language.js:27:24: error: Could not resolve "sugarss" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
node_modules/svelte-preprocess/dist/transformers/coffeescript.js:7:47: error: Could not resolve "coffeescript" (use "./coffeescript" to reference the file "node_modules/svelte-preprocess/dist/transformers/coffeescript.js")
node_modules/svelte-preprocess/dist/transformers/less.js:8:39: error: Could not resolve "less" (use "./less" to reference the file "node_modules/svelte-preprocess/dist/transformers/less.js")
node_modules/svelte-preprocess/dist/transformers/pug.js:8:38: error: Could not resolve "pug" (use "./pug" to reference the file "node_modules/svelte-preprocess/dist/transformers/pug.js")
node_modules/svelte-preprocess/dist/transformers/stylus.js:8:41: error: Could not resolve "stylus" (use "./stylus" to reference the file "node_modules/svelte-preprocess/dist/transformers/stylus.js")
Error: Build failed with 5 errors:
node_modules/svelte-preprocess/dist/modules/language.js:27:24: error: Could not resolve "sugarss" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
node_modules/svelte-preprocess/dist/transformers/coffeescript.js:7:47: error: Could not resolve "coffeescript" (use "./coffeescript" to reference the file "node_modules/svelte-preprocess/dist/transformers/coffeescript.js")
node_modules/svelte-preprocess/dist/transformers/less.js:8:39: error: Could not resolve "less" (use "./less" to reference the file "node_modules/svelte-preprocess/dist/transformers/less.js")
node_modules/svelte-preprocess/dist/transformers/pug.js:8:38: error: Could not resolve "pug" (use "./pug" to reference the file "node_modules/svelte-preprocess/dist/transformers/pug.js")
node_modules/svelte-preprocess/dist/transformers/stylus.js:8:41: error: Could not resolve "stylus" (use "./stylus" to reference the file "node_modules/svelte-preprocess/dist/transformers/stylus.js")
    at failureErrorWithLog (C:\Users\ns651\Documents\loose-lips-2.0\node_modules\esbuild\lib\main.js:1451:15)
    at C:\Users\ns651\Documents\loose-lips-2.0\node_modules\esbuild\lib\main.js:1131:28
    at runOnEndCallbacks (C:\Users\ns651\Documents\loose-lips-2.0\node_modules\esbuild\lib\main.js:921:63)
    at buildResponseToResult (C:\Users\ns651\Documents\loose-lips-2.0\node_modules\esbuild\lib\main.js:1129:7)
    at C:\Users\ns651\Documents\loose-lips-2.0\node_modules\esbuild\lib\main.js:1238:14
    at C:\Users\ns651\Documents\loose-lips-2.0\node_modules\esbuild\lib\main.js:609:9
    at handleIncomingPacket (C:\Users\ns651\Documents\loose-lips-2.0\node_modules\esbuild\lib\main.js:706:9)
    at Socket.readFromStdout (C:\Users\ns651\Documents\loose-lips-2.0\node_modules\esbuild\lib\main.js:576:7)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
file:///C:/Users/ns651/Documents/loose-lips-2.0/node_modules/@sveltejs/kit/dist/chunks/index.js:3354
                        throw new Error('Cannot close server before it is initialized');
                              ^

Error: Cannot close server before it is initialized
    at Watcher.close (file:///C:/Users/ns651/Documents/loose-lips-2.0/node_modules/@sveltejs/kit/dist/chunks/index.js:3354:10)
    at process.<anonymous> (file:///C:/Users/ns651/Documents/loose-lips-2.0/node_modules/@sveltejs/kit/dist/chunks/index.js:3198:9)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
    at process.exit (node:internal/process/per_thread:192:15)
    at handle_error (file:///C:/Users/ns651/Documents/loose-lips-2.0/node_modules/@sveltejs/kit/dist/cli.js:798:10)
    at file:///C:/Users/ns651/Documents/loose-lips-2.0/node_modules/@sveltejs/kit/dist/cli.js:850:4
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.14.0
```

**Comment by natesheehan** [comment]
My error when running the `npm run preview` - @Lewisthiverval are you getting something similar your end?

**Comment by Lewisthiverval** [comment]
Yes similar thing my end, tried a few things in vain

**Comment by natesheehan** [comment]
errors are still coming up but `npm run dev` is working on my local // will continue to investigate

**Comment by natesheehan** [comment]
hey @Lewisthiverval, i just pushed some changes to the main branch - let me know if these fix the issues on your side?

**Comment by Lewisthiverval** [comment]
it seems to be fixed !  hero
